name: Chromatic

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  publish-storybook:
    name: Publish Storybook to Chromatic
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Publish to Chromatic
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_TOKEN }}
